### ISSUE TITLE
Possible wrong epoch

### ISSUE THREAD

**Issue by sbernhard** [maccelf/foreman_kernel_care#20]
https://github.com/maccelf/foreman_kernel_care/blob/b926a5247f6b17f573e1a2a31b8441ac79515981/app/models/concerns/foreman_kernel_care/host_managed_extensions.rb#L41

The epoch should be used from the live kernel and not of the installed package.

**Comment by maccelf** [comment]
I am not sure we can get epoch from kernelcare util, so i think i should close this issue
