### ISSUE TITLE
Release new plugin version

### ISSUE THREAD

**Issue by nadjaheitmann** [maccelf/foreman_kernel_care#52]
@maccelf There have been a lot of changes since the last release of the plugin. What do you think about having a new version (maybe after merging the currently open PRs)?

If you want, you can leave the foreman-packaging part to me after publishing the rubygem.

**Comment by nadjaheitmann** [comment]
@maccelf Okay cool. I think it is important to add #51 as well as I messed up the original template. Ping me once you want me to do the packaging.

**Comment by nadjaheitmann** [comment]
@maccelf All PRs merged. Is there anything else that prevents a new version to be bumped?

**Comment by maccelf** [comment]
@nadjaheitmann sorry for the delay. I had a problem with my testing environment. I'll release a new version as soon as possible

**Comment by nadjaheitmann** [comment]
@maccelf Please merge this one first :) https://github.com/maccelf/foreman_kernel_care/pull/53

**Comment by maccelf** [comment]
@nadjaheitmann The New version of the plugin has been released to the [rubygem.org](https://rubygems.org/gems/foreman_kernel_care/versions/1.2.0)

**Comment by nadjaheitmann** [comment]
https://github.com/theforeman/foreman-packaging/pull/9838

Somehow, the Katello and REX dependencies disappeared from the spec file when I auto-generated it. Not sure why that happened.

**Comment by nadjaheitmann** [comment]
@maccelf I think, it would be a good idea to release a new minor version as we just fixed a lot of bugs after the release. Do you mind bumping a 1.2.1 and pushing to rubygem.org?

**Comment by maccelf** [comment]
@nadjaheitmann Yes, you're right I'll do it today

**Comment by maccelf** [comment]
@nadjaheitmann New version has been released

**Comment by nadjaheitmann** [comment]
@maccelf Thank you! This plugin is gonna picked up automatically by the foreman-packaging bot and there will be a packaging PR created automatically. Correct me if I am wrong @evgeni :)

**Comment by evgeni** [comment]
even better: it was already created and merged: https://github.com/theforeman/foreman-packaging/pull/9921 :))

**Comment by nadjaheitmann** [comment]
I am thrilled :) Something must be wrong with `the bot is automatically running on Sundays` :D

**Comment by evgeni** [comment]
Nah, nothing is wrong with that.
I just ran it manually yesterday, so yours also got picked up.

**Comment by nadjaheitmann** [comment]
It is super convenient not to do the PRs manually! Thank you!

**Comment by evgeni** [comment]
Glad you like it.

Btw, @maccelf, would you be interested in moving this repo to the foreman organization?

**Comment by maccelf** [comment]
@evgeni yes, it would be great

**Comment by evgeni** [comment]
if you invite me to this repo and give me admin perms, I can perform the transfer and re-add you as an repo-admin

**Comment by evgeni** [comment]
Hmm, I am now a collaborator, but I don't see the "settings" tab yet.

**Comment by evgeni** [comment]
or maybe, you can even try initiating the transfer yourself: https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository (this is new)

**Comment by maccelf** [comment]
@evgeni okay, got it

**Comment by maccelf** [comment]
@evgeni I accepted an invitation, but I still don't have rights to transfer the repository to the @theforeman organization
I have an error: Insufficient permission

**Comment by evgeni** [comment]
What if you enter "theforeman" in the "Specify an organization or username" field, instead of picking one from the "my orgs" list?

**Comment by maccelf** [comment]
Then I receive another error:  "You don’t have the permission to create public repositories on theforeman"

**Comment by maccelf** [comment]
I think I can transfer this repo to you and then you can transfer it to the foreman organization 😄

**Comment by evgeni** [comment]
or let's do that, yeah

**Comment by evgeni** [comment]
(did I mention that security features sometimes get in the way of using a thing?)

**Comment by evgeni** [comment]
welcome to your new home!

**Comment by maccelf** [comment]
Thank you !

**Comment by evgeni** [comment]
I've created a team, gave it admin perms on this repo, and added you to it.
Is there anyone else who should have elevated permissions?

**Comment by evgeni** [comment]
oh, and could you add https://rubygems.org/profiles/theforeman to the owners of the gem on rubygems.org? then we can do releases while you're on PTO ;)

**Comment by evgeni** [comment]
actually, you're the maintainer of the team, you can add people as you like yourself :)

**Comment by maccelf** [comment]
oh, okay, thank you :)
